language: python
python:
- 2.6
- 2.7
- 3.3
- 3.4
env:
- DJANGO=1.3
- DJANGO=1.4
- DJANGO=1.5
- DJANGO=1.6
- DJANGO=1.7
- DJANGO=master
matrix:
  exclude:
  - python: 2.6
    env: DJANGO=1.7
  - python: 2.6
    env: DJANGO=master
  - python: 3.3
    env: DJANGO=1.3
  - python: 3.3
    env: DJANGO=1.4
  - python: 3.4
    env: DJANGO=1.3
  - python: 3.4
    env: DJANGO=1.4
  allow_failures:
  - env: DJANGO=master
install:
- sudo apt-get install libevent-dev
- sudo apt-get install libzmq3-dev
- pip install -r test_requirements/requirements-django-$DJANGO.txt --use-mirrors
script:
- make test
notifications:
  email: false
  slack:
    secure: LcTTbTj0Px0/9Bs/S/uwbhkdULlj1YVdHnU8F/kOa3bq2QdCTptqB719r6BnzHvW+QGyADvDZ25UncVXFuLuHY67ZYfmyZ/H2cj0nrRSuYdPct0avhVbT/3s50GlNWK5qkfZDuqw6szYTFrgFWJcr5dl7Zf6Vovcvd38uaYOdno=
